language: python
sudo: false

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin

install:
  - luarocks install busted
  - luarocks install luacheck
  - if [[ "$LUA" == "lua=5.1"    ]]; then luarocks install stuart-sql; fi
  - if [[ "$LUA" == "lua=5.2"    ]]; then luarocks install stuart-sql; fi
  - if [[ "$LUA" == "lua=5.3"    ]]; then luarocks install stuart; fi
  - if [[ "$LUA" == "luajit=2.0" ]]; then luarocks install stuart; fi
  - if [[ "$LUA" == "luajit=2.1" ]]; then luarocks install stuart; fi

script:
  - luacheck --std max+busted --codes src spec examples --no-self --ignore 213 311 611 631
  - busted --verbose --defer-print --no-auto-insulate
